import localFont from "next/font/local";

import Footer from "./components/navigation/footer";
import dynamic from "next/dynamic";
import NaviBar from "./components/navigation/navbar/NaviBar";
import Providers from "./Providers.js";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "El Cronopio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers>
          <NaviBar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}

// export default dynamic(() => Promise.resolve(RootLayout), { ssr: false })
